version: '3.9'

services:
  omt-streets-gl-style:
    image: ttungbmt/omt-streets-gl-style:${OMTS_VERSION}-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "${OMTS_FORWARD_PORT}:80"